// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_cloud_logic : 'enable',
aws_cloud_logic_custom : '[{"id":"pa53f2zm9c","name":"ReactSample","description":"","endpoint":"https://pa53f2zm9c.execute-api.eu-central-1.amazonaws.com/Development","region":"eu-central-1","paths":["/items","/items/123"]}]',
aws_cognito_identity_pool_id : 'eu-central-1:59fe3d85-26ec-4707-9ce4-f10c7d0cbcd9',
aws_cognito_region : 'eu-central-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'reactsample-hosting-mobilehub-1471598003',
aws_content_delivery_bucket_region : 'eu-central-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd23y67m546bmwg.cloudfront.net',
aws_dynamodb : 'enable',
aws_dynamodb_all_tables_region : 'eu-central-1',
aws_dynamodb_table_schemas : '[{"tableName":"reactsample-mobilehub-1471598003-bbq_orders","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"eu-central-1","hashKey":"id"},{"tableName":"reactsample-mobilehub-1471598003-bbq_menu_item","attributes":[{"name":"restaurant_id","type":"S"},{"name":"id","type":"S"}],"indexes":[],"region":"eu-central-1","hashKey":"restaurant_id","rangeKey":"id"},{"tableName":"reactsample-mobilehub-1471598003-bbq_restaurants","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"eu-central-1","hashKey":"id"}]',
aws_mandatory_sign_in : 'enable',
aws_project_id : 'aab9a527-b7ba-4458-bb63-39d986bb9023',
aws_project_name : 'react-sample',
aws_project_region : 'eu-central-1',
aws_resource_bucket_name : 'reactsample-deployments-mobilehub-1471598003',
aws_resource_name_prefix : 'reactsample-mobilehub-1471598003',
aws_sign_in_enabled : 'enable',
aws_user_pools : 'enable',
aws_user_pools_id : 'eu-central-1_x8XJfcMo9',
aws_user_pools_mfa_type : 'ON',
aws_user_pools_web_client_id : '4fqsdvsuok1an7vmr2h1k56unh',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});